# Generated by Django 5.2.10 on 2026-06-09 16:29

from django.db import migrations, models


def rename_ranks(apps, schema_editor):
    UserProfile = apps.get_model('mainapp', 'UserProfile')
    # CM → CEM  (Chief Executive Manager)
    UserProfile.objects.filter(rank='CM').update(rank='CEM')
    # old BH was imported from RETAILER (11%) — now Retailer = RT
    # new BH = Business Head (43%), which is a different set of users
    # so rename all existing BH (the old retailer ones) → RT
    UserProfile.objects.filter(rank='BH').update(rank='RT')


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_mlm_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(blank=True, choices=[('FC', 'Fashion Consultant'), ('FA', 'Fashion Associate'), ('FEM', 'Fashion Executive Manager'), ('CEM', 'Chief Executive Manager'), ('BH', 'Business Head'), ('BA', 'Business Ambassador'), ('RT', 'Retailer')], max_length=10, null=True),
        ),
        migrations.RunPython(rename_ranks, migrations.RunPython.noop),
    ]
