# Generated by Django 5.2.10 on 2026-06-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_update_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
